### ISSUE TITLE
关于伯尔顿

### ISSUE THREAD

**Issue by Viviane1999** [orz12/Hints-for-Realm-Defense-Player#9]
请问伯尔顿阶段六中的黑岩巨人，需要预先拥有黑岩巨人吗？

**Comment by orz12** [comment]
需要。召唤的黑岩巨人是自己所拥有的。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Viviane1999** [comment]
多谢多谢

**Comment by orz12** [comment]
> 多谢多谢

欢迎加群向大佬提问哟~这篇攻略有点久没更新了
